// GENERATED by scripts/build-issue-knowledge.mjs from data/historic-tickets.json
// (464 historic reports, 29 issue families). Do not edit by hand —
// re-run `node scripts/build-issue-knowledge.mjs` after refreshing the export.
// Used at runtime by src/lib/issue-knowledge.ts; never imported into the tickets table.

export type IssuePattern = {
  category: string;
  subcategory: string;
  count: number;
  keywords: string[];
  rootCauses: string[];
  actions: string[];
  owners: string[];
  studios: string[];
  priorityMode: string;
};

export const ISSUE_PATTERNS: IssuePattern[] = [
  {
    "category": "Operating Systems",
    "subcategory": "Internal Operations Memo",
    "count": 156,
    "keywords": [
      "memo",
      "operations",
      "systems",
      "reported",
      "spans",
      "messages"
    ],
    "rootCauses": [
      "Internal operational process or system issue."
    ],
    "actions": [
      "Review and address the reported operational issue.",
      "Coordinate with relevant department head."
    ],
    "owners": [
      "Shifa Ali",
      "Jimmeey"
    ],
    "studios": [
      "Indiranagar / Kenkere (Bengaluru)",
      "Bandra / Juhu"
    ],
    "priorityMode": "Low"
  },
  {
    "category": "Studio Amenities and Facilities",
    "subcategory": "Studio Temperature / AC",
    "count": 58,
    "keywords": [
      "ac",
      "air conditioning",
      "temperature",
      "hot",
      "heat",
      "cooling",
      "stuffy",
      "humid",
      "warm",
      "servicing"
    ],
    "rootCauses": [
      "Facility maintenance or hygiene concern.",
      "Environmental discomfort (AC management) and Schedule mismatch/Capacity constraints for high-demand classes."
    ],
    "actions": [
      "Inspect reported facility issue.",
      "Schedule maintenance if required."
    ],
    "owners": [
      "Studio Management",
      "Shifa Ali"
    ],
    "studios": [
      "Bandra / Juhu",
      "Kwality House, Kemps Corner"
    ],
    "priorityMode": "Low"
  },
  {
    "category": "Class Experience",
    "subcategory": "Class Experience Feedback",
    "count": 35,
    "keywords": [
      "class experience",
      "intensity",
      "crowded",
      "music",
      "too fast",
      "too slow",
      "beginner",
      "feedback",
      "quality",
      "experience"
    ],
    "rootCauses": [
      "Class experience did not meet client expectations."
    ],
    "actions": [
      "Acknowledge feedback from client.",
      "Brief instructor on client preferences."
    ],
    "owners": [
      "Shipra Bhika",
      "Studio Management"
    ],
    "studios": [
      "Bandra / Juhu",
      "Indiranagar / Kenkere (Bengaluru)"
    ],
    "priorityMode": "Low"
  },
  {
    "category": "Operating Systems",
    "subcategory": "Marketing Campaign Launch & Internal Alignment",
    "count": 15,
    "keywords": [
      "campaign",
      "instagram",
      "social media",
      "post",
      "creative",
      "approval",
      "launch",
      "brand",
      "alignment",
      "marketing"
    ],
    "rootCauses": [
      "Internal operational process or system issue.",
      "Lack of consensus on marketing strategy between operations and implementation teams, coupled with content"
    ],
    "actions": [
      "Review and address the reported operational issue.",
      "Coordinate with relevant department head."
    ],
    "owners": [
      "Shifa Ali",
      "Ayesha"
    ],
    "studios": [
      "Indiranagar / Kenkere (Bengaluru)"
    ],
    "priorityMode": "Low"
  },
  {
    "category": "Miscellaneous",
    "subcategory": "Internal Session Reporting / Post-Class Feedback",
    "count": 14,
    "keywords": [
      "class experience",
      "intensity",
      "crowded",
      "music",
      "too fast",
      "too slow",
      "beginner",
      "feedback",
      "post-class",
      "session"
    ],
    "rootCauses": [
      "Miscellaneous operational issue.",
      "Standard internal reporting procedure for private hosted events."
    ],
    "actions": [
      "Review thread and determine appropriate action.",
      "Assign to relevant department."
    ],
    "owners": [
      "Studio Management",
      "Reyna Jagtiani"
    ],
    "studios": [
      "Bandra / Juhu",
      "Indiranagar / Kenkere (Bengaluru)"
    ],
    "priorityMode": "Low"
  },
  {
    "category": "Trainer Feedback",
    "subcategory": "Punctuality and Client Engagement",
    "count": 13,
    "keywords": [
      "late",
      "punctuality",
      "rude",
      "attitude",
      "engagement",
      "conduct",
      "behaviour",
      "no-show",
      "left early",
      "phone"
    ],
    "rootCauses": [
      "Staff conduct or performance concern.",
      "Lack of adherence to studio SOPs regarding pre-class preparation and client interaction protocols."
    ],
    "actions": [
      "Speak with trainer privately regarding the incident.",
      "Document complaint in HR file."
    ],
    "owners": [
      "Shipra Bhika",
      "Studio Management"
    ],
    "studios": [
      "Bandra / Juhu",
      "Kwality House, Kemps Corner"
    ],
    "priorityMode": "High"
  },
  {
    "category": "Scheduling",
    "subcategory": "Class Availability / Variety",
    "count": 11,
    "keywords": [
      "variety",
      "availability",
      "booking",
      "scheduling",
      "mrigakshi",
      "jaiswal"
    ],
    "rootCauses": [
      "Scheduling conflict or booking process failure.",
      "Inconsistency in evening programming across different studio locations (Bandra vs."
    ],
    "actions": [
      "Verify booking records.",
      "Coordinate with scheduling team."
    ],
    "owners": [
      "Studio Management",
      "Jimmeey"
    ],
    "studios": [
      "Bandra / Juhu",
      "Kwality House, Kemps Corner"
    ],
    "priorityMode": "Low"
  },
  {
    "category": "Operating Systems",
    "subcategory": "Internal Campaign Coordination",
    "count": 11,
    "keywords": [
      "campaign",
      "instagram",
      "social media",
      "post",
      "creative",
      "approval",
      "launch",
      "brand",
      "coordination",
      "systems"
    ],
    "rootCauses": [
      "Internal operational process or system issue.",
      "Pending confirmation from Trainers/Ops on program mechanics and cross-studio policy standardization."
    ],
    "actions": [
      "Review and address the reported operational issue.",
      "Coordinate with relevant department head."
    ],
    "owners": [
      "Shifa Ali",
      "Jimmeey"
    ],
    "studios": [
      "Indiranagar / Kenkere (Bengaluru)"
    ],
    "priorityMode": "Low"
  },
  {
    "category": "Scheduling",
    "subcategory": "Hosted Class / Instructor Swap Request",
    "count": 11,
    "keywords": [
      "hosted class",
      "instructor swap",
      "cover",
      "substitute",
      "swap",
      "instructor",
      "booking",
      "request",
      "scheduling",
      "hosted"
    ],
    "rootCauses": [
      "Scheduling conflict or booking process failure.",
      "Client request for premium experience/instructor expertise for a group booking involving potential brand"
    ],
    "actions": [
      "Verify booking records.",
      "Coordinate with scheduling team."
    ],
    "owners": [
      "Studio Management",
      "Reyna Jagtiani"
    ],
    "studios": [
      "Bandra / Juhu",
      "Kwality House, Kemps Corner"
    ],
    "priorityMode": "Low"
  },
  {
    "category": "Studio Amenities and Facilities",
    "subcategory": "Boutique / Retail Offerings",
    "count": 8,
    "keywords": [
      "boutique",
      "retail",
      "merchandise",
      "stock",
      "grip socks",
      "offerings",
      "hygiene",
      "facility",
      "maverick"
    ],
    "rootCauses": [
      "Facility maintenance or hygiene concern.",
      "Client identified a gap in the current retail/amenity offering regarding hydration supplements."
    ],
    "actions": [
      "Inspect reported facility issue.",
      "Schedule maintenance if required."
    ],
    "owners": [
      "Shifa Ali",
      "Saachi Shetty"
    ],
    "studios": [
      "Kwality House, Kemps Corner"
    ],
    "priorityMode": "Low"
  },
  {
    "category": "Operating Systems",
    "subcategory": "Marketing / Operational Workflow",
    "count": 7,
    "keywords": [
      "campaign",
      "instagram",
      "social media",
      "post",
      "creative",
      "approval",
      "launch",
      "brand",
      "workflow",
      "marketing"
    ],
    "rootCauses": [
      "Internal operational process or system issue.",
      "Standard seasonal campaign planning and execution cycle."
    ],
    "actions": [
      "Review and address the reported operational issue.",
      "Coordinate with relevant department head."
    ],
    "owners": [
      "Saachi Shetty",
      "Ayesha"
    ],
    "studios": [
      "Indiranagar / Kenkere (Bengaluru)"
    ],
    "priorityMode": "Low"
  },
  {
    "category": "Safety and Security",
    "subcategory": "Theft / Missing Items",
    "count": 6,
    "keywords": [
      "theft",
      "stolen",
      "missing",
      "lost",
      "wallet",
      "phone",
      "locker",
      "valuables",
      "items",
      "injury"
    ],
    "rootCauses": [
      "Physical incident or security breach at studio.",
      "Reported security breach or theft involving a locker bypass via master code."
    ],
    "actions": [
      "Review incident details with studio manager.",
      "File formal incident report."
    ],
    "owners": [
      "Shipra Bhika",
      "Jimmeey"
    ],
    "studios": [
      "Bandra / Juhu"
    ],
    "priorityMode": "High"
  },
  {
    "category": "Operating Systems",
    "subcategory": "Payment Reconciliation",
    "count": 6,
    "keywords": [
      "payment",
      "reconciliation",
      "pos",
      "settlement",
      "invoice",
      "billing",
      "refund",
      "charges",
      "deposit",
      "payments"
    ],
    "rootCauses": [
      "Internal operational process or system issue.",
      "Delayed internal communication/reconciliation process between the sales/operations team and the finance"
    ],
    "actions": [
      "Review and address the reported operational issue.",
      "Coordinate with relevant department head."
    ],
    "owners": [
      "Gaurav Sogam",
      "Shifa Ali"
    ],
    "studios": [
      "Bandra / Juhu"
    ],
    "priorityMode": "Medium"
  },
  {
    "category": "Operating Systems",
    "subcategory": "Partnership / Collaboration Approval",
    "count": 6,
    "keywords": [
      "collaboration",
      "approval",
      "partnership",
      "systems",
      "anniversary",
      "spans"
    ],
    "rootCauses": [
      "Internal operational process or system issue.",
      "Lack of a standardized pricing tier for 'Studio Takeovers' vs."
    ],
    "actions": [
      "Review and address the reported operational issue.",
      "Coordinate with relevant department head."
    ],
    "owners": [
      "Shifa Ali",
      "Saachi Shetty"
    ],
    "studios": [],
    "priorityMode": "Low"
  },
  {
    "category": "Operating Systems",
    "subcategory": "Performance Review / Payroll",
    "count": 5,
    "keywords": [
      "payroll",
      "performance review",
      "hr",
      "zoho",
      "salary",
      "appraisal",
      "review",
      "performance",
      "gondaa",
      "increment"
    ],
    "rootCauses": [
      "Internal operational process or system issue.",
      "Standard bi-annual performance review cycle & increment determination."
    ],
    "actions": [
      "Review and address the reported operational issue.",
      "Coordinate with relevant department head."
    ],
    "owners": [
      "Jimmeey Gondaa",
      "Jimmeey Gondaa / Shifa Ali"
    ],
    "studios": [],
    "priorityMode": "Low"
  },
  {
    "category": "Operating Systems",
    "subcategory": "Standard Operating Procedures (SOP)",
    "count": 5,
    "keywords": [
      "sop",
      "checklist",
      "procedure",
      "handover",
      "shift",
      "process",
      "procedures",
      "operating",
      "standard",
      "systems"
    ],
    "rootCauses": [
      "Internal operational process or system issue.",
      "Standardizing internal communication to prevent data gaps in class reporting."
    ],
    "actions": [
      "Review and address the reported operational issue.",
      "Coordinate with relevant department head."
    ],
    "owners": [
      "Zahur / Zaheer",
      "Zahur Shaikh"
    ],
    "studios": [],
    "priorityMode": "Critical"
  },
  {
    "category": "Safety and Security",
    "subcategory": "Incident Report",
    "count": 5,
    "keywords": [
      "injury",
      "injured",
      "fell",
      "slipped",
      "pain",
      "swelling",
      "sprain",
      "safety",
      "first aid",
      "ambulance"
    ],
    "rootCauses": [
      "Physical incident or security breach at studio."
    ],
    "actions": [
      "Review incident details with studio manager.",
      "File formal incident report."
    ],
    "owners": [
      "Studio Management",
      "Shipra Bhika"
    ],
    "studios": [
      "Bandra / Juhu",
      "Kwality House, Kemps Corner"
    ],
    "priorityMode": "High"
  },
  {
    "category": "Operating Systems",
    "subcategory": "Data Accuracy & CRM Integration",
    "count": 4,
    "keywords": [
      "momence",
      "crm",
      "data",
      "sync",
      "inaccurate",
      "bookings",
      "waitlist",
      "integration",
      "accuracy",
      "systems"
    ],
    "rootCauses": [
      "Internal operational process or system issue.",
      "CRM/Tech Stack failure (Momence) failing to provide reliable retention metrics, combined with behavioral"
    ],
    "actions": [
      "Review and address the reported operational issue.",
      "Coordinate with relevant department head."
    ],
    "owners": [
      "Jimmeey",
      "Mitali Kumar"
    ],
    "studios": [
      "Indiranagar / Kenkere (Bengaluru)"
    ],
    "priorityMode": "Low"
  },
  {
    "category": "Scheduling",
    "subcategory": "Class Cancellation & Schedule Imbalance",
    "count": 4,
    "keywords": [
      "cancelled",
      "reschedule",
      "schedule",
      "timetable",
      "capacity",
      "waitlist",
      "slots",
      "empty class",
      "cancellation",
      "imbalance"
    ],
    "rootCauses": [
      "Scheduling conflict or booking process failure.",
      "Class cancellation without a substitute trainer, compounded by a restrictive weekly schedule for evening-only"
    ],
    "actions": [
      "Verify booking records.",
      "Coordinate with scheduling team."
    ],
    "owners": [
      "Jimmeey",
      "Studio Management"
    ],
    "studios": [
      "Indiranagar / Kenkere (Bengaluru)"
    ],
    "priorityMode": "High"
  },
  {
    "category": "Scheduling",
    "subcategory": "Workshop Scheduling / Capacity Planning",
    "count": 4,
    "keywords": [
      "cancelled",
      "reschedule",
      "schedule",
      "timetable",
      "capacity",
      "waitlist",
      "slots",
      "empty class",
      "workshop",
      "planning"
    ],
    "rootCauses": [
      "Scheduling conflict or booking process failure.",
      "Customer feedback indicating a need for technical form correction in Bandra, coupled with internal concerns"
    ],
    "actions": [
      "Verify booking records.",
      "Coordinate with scheduling team."
    ],
    "owners": [
      "Shifa Ali",
      "Mrigakshi Jaiswal"
    ],
    "studios": [
      "Indiranagar / Kenkere (Bengaluru)",
      "Bandra / Juhu"
    ],
    "priorityMode": "Low"
  },
  {
    "category": "Trainer Feedback",
    "subcategory": "Trainer Performance",
    "count": 4,
    "keywords": [
      "conduct",
      "performance",
      "trainer",
      "trainers",
      "jimmeey",
      "reported"
    ],
    "rootCauses": [
      "Staff conduct or performance concern."
    ],
    "actions": [
      "Speak with trainer privately regarding the incident.",
      "Document complaint in HR file."
    ],
    "owners": [
      "Jimmeey Gondaa",
      "Shipra Bhika"
    ],
    "studios": [
      "Bandra / Juhu"
    ],
    "priorityMode": "High"
  },
  {
    "category": "Operating Systems",
    "subcategory": "Zoho Shift Scheduling / HRIS Access",
    "count": 3,
    "keywords": [
      "sop",
      "checklist",
      "procedure",
      "handover",
      "shift",
      "process",
      "payroll",
      "performance review",
      "hr",
      "zoho"
    ],
    "rootCauses": [
      "Internal operational process or system issue.",
      "Incorrect configuration or permission settings within the Zoho roster/shift management module."
    ],
    "actions": [
      "Review and address the reported operational issue.",
      "Coordinate with relevant department head."
    ],
    "owners": [
      "Jimmeey",
      "Jimmeey Gondaa"
    ],
    "studios": [],
    "priorityMode": "Low"
  },
  {
    "category": "Operating Systems",
    "subcategory": "Creative Asset Production",
    "count": 3,
    "keywords": [
      "campaign",
      "instagram",
      "social media",
      "post",
      "creative",
      "approval",
      "launch",
      "brand",
      "design",
      "asset"
    ],
    "rootCauses": [
      "Internal operational process or system issue.",
      "Communication gap between internal leadership requirements and the external consultant's initial brief,"
    ],
    "actions": [
      "Review and address the reported operational issue.",
      "Coordinate with relevant department head."
    ],
    "owners": [
      "Shifa Ali",
      "Ayesha"
    ],
    "studios": [],
    "priorityMode": "Low"
  },
  {
    "category": "Operating Systems",
    "subcategory": "Handover / Shift Reporting",
    "count": 3,
    "keywords": [
      "sop",
      "checklist",
      "procedure",
      "handover",
      "shift",
      "process",
      "systems",
      "november",
      "shifa",
      "reported"
    ],
    "rootCauses": [
      "Internal operational process or system issue."
    ],
    "actions": [
      "Review and address the reported operational issue.",
      "Coordinate with relevant department head."
    ],
    "owners": [
      "Shifa Ali",
      "Jimmeey"
    ],
    "studios": [],
    "priorityMode": "Medium"
  },
  {
    "category": "Class Experience",
    "subcategory": "Trainer Performance / Intensity Level",
    "count": 2,
    "keywords": [
      "class experience",
      "intensity",
      "crowded",
      "music",
      "too fast",
      "too slow",
      "beginner",
      "feedback",
      "level",
      "performance"
    ],
    "rootCauses": [
      "Trainer performance disparity; new/younger trainers not meeting the intensity expectations set by veteran",
      "Class experience did not meet client expectations."
    ],
    "actions": [
      "Schedule a formal performance review/alignment session for Simonelle with Vivaran.",
      "Conduct a 'blind' audit of Simonelle’s upcoming evening classes specifically for intensity and"
    ],
    "owners": [
      "Mrigakshi Jaiswal",
      "Mitali Kumar"
    ],
    "studios": [
      "Bandra / Juhu"
    ],
    "priorityMode": "High"
  },
  {
    "category": "Studio Amenities and Facilities",
    "subcategory": "Locker Security & Maintenance",
    "count": 2,
    "keywords": [
      "theft",
      "stolen",
      "missing",
      "lost",
      "wallet",
      "phone",
      "locker",
      "valuables",
      "security"
    ],
    "rootCauses": [
      "Locker hardware reliability issues and a recent unidentified security incident.",
      "Facility maintenance or hygiene concern."
    ],
    "actions": [
      "Investigate the 'recent incident' mentioned to ensure no theft occurred; if it did, assess legal",
      "Schedule a repeating calendar task for Zahur for the monthly master code rotation."
    ],
    "owners": [
      "Zahur Shaikh",
      "Jimmeey Gondaa"
    ],
    "studios": [
      "Bandra / Juhu"
    ],
    "priorityMode": "High"
  },
  {
    "category": "Trainer Feedback",
    "subcategory": "Client Conflict Management",
    "count": 2,
    "keywords": [
      "trainer",
      "client"
    ],
    "rootCauses": [
      "Client overstepping social boundaries and undermining trainer authority/expertise.",
      "Staff conduct or performance concern."
    ],
    "actions": [
      "Review 'similar instances' mentioned by Jimmeey to establish a formal history of behavioral issues.",
      "Schedule a private consultation with Mallika Mhatre to discuss studio community guidelines and"
    ],
    "owners": [
      "Jimmeey Gondaa",
      "Shipra Bhika"
    ],
    "studios": [
      "Bandra / Juhu"
    ],
    "priorityMode": "High"
  },
  {
    "category": "Operating Systems",
    "subcategory": "Late Entry Policy Enforcement",
    "count": 2,
    "keywords": [
      "late",
      "punctuality",
      "rude",
      "attitude",
      "engagement",
      "conduct",
      "behaviour",
      "no-show",
      "left early",
      "phone"
    ],
    "rootCauses": [
      "Strict enforcement of the 10-minute late policy during a period of high emotional stress for the customer,",
      "Miscellaneous operational issue."
    ],
    "actions": [
      "Jimmeey to investigate the 'FIT class' incident involving Raunak to verify policy consistency.",
      "Reach out to Shona Barua directly to offer condolences regarding her father and provide a one-time"
    ],
    "owners": [
      "Jimmeey",
      "Vivaran Dhasmana"
    ],
    "studios": [],
    "priorityMode": "Medium"
  },
  {
    "category": "Operating Systems",
    "subcategory": "SOP / Operational Checklist Alignment",
    "count": 2,
    "keywords": [
      "sop",
      "checklist",
      "procedure",
      "handover",
      "shift",
      "process",
      "shifa",
      "operational",
      "internal"
    ],
    "rootCauses": [
      "Drafting of operational documents without clearly defined user personas or responsibility boundaries between",
      "Internal operational process or system issue."
    ],
    "actions": [
      "Shifa to review Mitali's comments in the Google Doc link.",
      "Define specific RACI (Responsible, Accountable, Consulted, Informed) for each line item in the"
    ],
    "owners": [
      "Shifa Ali / Mitali Kumar",
      "Shifa Ali"
    ],
    "studios": [],
    "priorityMode": "Medium"
  }
];

export const OWNER_PRIORS: Record<string, string[]> = {
  "Operating Systems": [
    "Shifa Ali",
    "Jimmeey",
    "Ayesha"
  ],
  "Operating Systems|Internal Operations Memo": [
    "Shifa Ali",
    "Jimmeey"
  ],
  "Studio Amenities and Facilities": [
    "Shifa Ali",
    "Studio Management",
    "Saachi Shetty"
  ],
  "Studio Amenities and Facilities|Studio Temperature / AC": [
    "Studio Management",
    "Shifa Ali"
  ],
  "Class Experience": [
    "Shipra Bhika",
    "Studio Management",
    "Mrigakshi Jaiswal"
  ],
  "Class Experience|Class Experience Feedback": [
    "Shipra Bhika",
    "Studio Management"
  ],
  "Operating Systems|Marketing Campaign Launch & Internal Alignment": [
    "Shifa Ali",
    "Ayesha"
  ],
  "Miscellaneous": [
    "Studio Management",
    "Reyna Jagtiani"
  ],
  "Miscellaneous|Internal Session Reporting / Post-Class Feedback": [
    "Studio Management",
    "Reyna Jagtiani"
  ],
  "Trainer Feedback": [
    "Shipra Bhika",
    "Studio Management",
    "Jimmeey Gondaa"
  ],
  "Trainer Feedback|Punctuality and Client Engagement": [
    "Shipra Bhika",
    "Studio Management"
  ],
  "Scheduling": [
    "Studio Management",
    "Jimmeey",
    "Reyna Jagtiani"
  ],
  "Scheduling|Class Availability / Variety": [
    "Studio Management",
    "Jimmeey"
  ],
  "Operating Systems|Internal Campaign Coordination": [
    "Shifa Ali",
    "Jimmeey"
  ],
  "Scheduling|Hosted Class / Instructor Swap Request": [
    "Studio Management",
    "Reyna Jagtiani"
  ],
  "Studio Amenities and Facilities|Boutique / Retail Offerings": [
    "Shifa Ali",
    "Saachi Shetty"
  ],
  "Operating Systems|Marketing / Operational Workflow": [
    "Saachi Shetty",
    "Ayesha"
  ],
  "Safety and Security": [
    "Shipra Bhika",
    "Jimmeey",
    "Studio Management"
  ],
  "Safety and Security|Theft / Missing Items": [
    "Shipra Bhika",
    "Jimmeey"
  ],
  "Operating Systems|Payment Reconciliation": [
    "Gaurav Sogam",
    "Shifa Ali"
  ],
  "Operating Systems|Partnership / Collaboration Approval": [
    "Shifa Ali",
    "Saachi Shetty"
  ],
  "Operating Systems|Performance Review / Payroll": [
    "Jimmeey Gondaa",
    "Jimmeey Gondaa / Shifa Ali"
  ],
  "Operating Systems|Standard Operating Procedures (SOP)": [
    "Zahur / Zaheer",
    "Zahur Shaikh"
  ],
  "Safety and Security|Incident Report": [
    "Studio Management",
    "Shipra Bhika"
  ],
  "Operating Systems|Data Accuracy & CRM Integration": [
    "Jimmeey",
    "Mitali Kumar"
  ],
  "Scheduling|Class Cancellation & Schedule Imbalance": [
    "Jimmeey",
    "Studio Management"
  ],
  "Scheduling|Workshop Scheduling / Capacity Planning": [
    "Shifa Ali",
    "Mrigakshi Jaiswal"
  ],
  "Trainer Feedback|Trainer Performance": [
    "Jimmeey Gondaa",
    "Shipra Bhika"
  ],
  "Operating Systems|Zoho Shift Scheduling / HRIS Access": [
    "Jimmeey",
    "Jimmeey Gondaa"
  ],
  "Operating Systems|Creative Asset Production": [
    "Shifa Ali",
    "Ayesha"
  ],
  "Operating Systems|Handover / Shift Reporting": [
    "Shifa Ali",
    "Jimmeey"
  ],
  "Class Experience|Trainer Performance / Intensity Level": [
    "Mrigakshi Jaiswal",
    "Mitali Kumar"
  ],
  "Studio Amenities and Facilities|Locker Security & Maintenance": [
    "Zahur Shaikh",
    "Jimmeey Gondaa"
  ],
  "Trainer Feedback|Client Conflict Management": [
    "Jimmeey Gondaa",
    "Shipra Bhika"
  ],
  "Operating Systems|Late Entry Policy Enforcement": [
    "Jimmeey",
    "Vivaran Dhasmana"
  ],
  "Operating Systems|SOP / Operational Checklist Alignment": [
    "Shifa Ali / Mitali Kumar",
    "Shifa Ali"
  ]
};

export const CORPUS = {
  "total": 464,
  "span": "2022-06-21 to 2026-05-02",
  "topIssues": [
    "Internal Operations Memo (156)",
    "Studio Temperature / AC (58)",
    "Class Experience Feedback (35)",
    "Marketing Campaign Launch & Internal Alignment (15)",
    "Internal Session Reporting / Post-Class Feedback (14)",
    "Punctuality and Client Engagement (13)"
  ],
  "longTail": 57
} as const;
