export type CategoryMeta = {
  name: string;
  icon: string;
  accent: string;
  team: string;
  blurb: string;
  defaultPriority: Priority;
  followUps: FollowUpKey[];
};

export type Priority = "Low" | "Medium" | "High" | "Critical";
export type Status = "Open" | "In Progress" | "Awaiting Info" | "Resolved" | "Closed";

export type FollowUpKey =
  | "trainer"
  | "class"
  | "location"
  | "system"
  | "membership"
  | "risk";

export const PRIORITIES: Priority[] = ["Low", "Medium", "High", "Critical"];
export const STATUSES: Status[] = [
  "Open",
  "In Progress",
  "Awaiting Info",
  "Resolved",
  "Closed",
];

export const SLA_HOURS: Record<Priority, number> = {
  Critical: 4,
  High: 24,
  Medium: 72,
  Low: 168,
};

export const TAXONOMY: Record<string, string[]> = {
  Scheduling: [
    "Time Change",
    "Level Change",
    "Additional Classes",
    "Trainer Preferences",
    "Class Capacity Issues",
    "Waitlist Concerns",
    "Studio Timings",
    "Session Length",
    "Cancellation Policy",
    "Booking Restrictions",
    "Class Substitutions",
    "Trainer Substitutions",
    "Last-minute Cancellations",
    "Late Arrival Policy",
    "Special Request Accommodations",
    "Early Morning/Late Night Class Availability",
    "Weekend vs. Weekday Class Balance",
    "Rescheduling Flexibility",
    "Booking Confirmation Issues",
    "Holiday and Festival Class Planning",
  ],
  "Class Experience": [
    "Bad Odour",
    "Audio Issues",
    "Studio Temperature Too Hot/Cold",
    "Overcrowding in Class",
    "Class Flow and Pacing",
    "Modifications in Routine",
    "Engagement with Clients",
    "Hands-on Adjustments",
    "Demonstration and Visual Cues",
    "Knowledge and Competence",
    "Brand Language Usage",
    "Grooming and Appearance",
    "Attendance for Workshops",
    "Attendance for Meetings",
    "Class Format Satisfaction",
    "Class Duration Suitability",
    "Instructor Energy and Motivation",
    "Class Variety and Themes",
    "Adjustments for Different Fitness Levels",
    "Challenges in Following Instructor",
  ],
  "Trainer Feedback": [
    "Trainer Forgot Names",
    "Class Intensity Too High/Low",
    "Trainer Hygiene",
    "Trainer Punctuality Issues",
    "Trainer Behaviour",
    "Modifications in Routine",
    "Engagement with Clients",
    "Hands-on Adjustments",
    "Demonstration and Visual Cues",
    "Knowledge and Competence",
    "Brand Language Usage",
    "Pre and Post-Class Outreach",
    "Trainer Availability",
    "Feedback Handling",
    "Emergency Preparedness",
    "Trainer Focus on Individual Needs",
    "Class Ending on Time",
    "Trainer Encouragement",
    "Injury Prevention and Safety",
    "Too Many Corrections vs. Too Few",
  ],
  "Repair and Maintenance": [
    "AC and HVAC Issues",
    "TFA Malfunction",
    "Lighting Issues",
    "Studio System Malfunction",
    "Pest Control Needed",
    "Staff Uniforms Not Clean",
    "Toiletries and Supplies Low",
    "Towel Availability Issues",
    "Plumbing Leaks",
    "General Maintenance Delays",
    "Uncomfortable Lounge Seating",
    "Air Fresheners Too Strong",
    "Music System Too Loud/Low",
    "Vending Machine Out of Stock",
    "Additional Waiting Area Seating",
    "Door Lock Issues",
    "Fire Safety Compliance",
    "Water Dispenser Issues",
    "Dust and Mold in Corners",
    "Broken Equipment Not Repaired",
  ],
  "Studio Amenities and Facilities": [
    "Studio Odour and Aroma",
    "Cleanliness and Hygiene",
    "Ventilation Poor",
    "Air Quality Poor",
    "Valet Issues",
    "Locker Availability",
    "Shower Water Pressure",
    "Steam Room Not Working",
    "Boutique Availability Issues",
    "Wi-Fi Slow",
    "Integration Issues",
    "Lost and Found Disorganization",
    "Availability of Gym Accessories",
    "Fitness Challenges and Rewards",
    "Additional Membership Perks",
    "Smoothie Bar and Refreshments",
    "Member Lounge Cleanliness",
    "Community Events and Social Engagement",
    "Holiday-Themed Classes",
    "Sustainable and Eco-Friendly Practices",
  ],
  "Operating Systems": [
    "Moments Notice",
    "Stripe and Razorpay",
    "Yellow Messenger",
    "Website Glitches",
    "Router Connectivity",
    "iPad Functionality",
    "Cash Counting Machine Issues",
    "POS System Malfunctions",
    "CRM System Errors",
    "Data Security Issues",
    "Technical Assistance",
    "Difficulty Tracking Sessions",
    "System Delays",
    "Software Bugs",
    "Mobile App UI/UX Issues",
    "Attendance Record Discrepancies",
    "Missed Sessions Not Recorded",
    "Mobile App Freezing",
    "Delayed Notifications",
    "Error in Class Listings",
    "Payment Reconciliation Discrepancy",
  ],
  "Tech Issues": [
    "Laptops Not Functioning",
    "Speakers Static Noise",
    "Mic Not Working",
    "Phones Not Working",
    "App Performance Bugs",
    "Booking System Errors",
    "Password and Login Issues",
    "Payment Processing Delays",
    "Online Class Streaming Buffering",
    "Notifications Not Received",
    "Auto-Debit Incorrect Charges",
    "Social Media Glitches",
    "Wrong Class Bookings",
    "Incorrect Charges on Account",
    "Studio Music Preferences",
    "Camera Surveillance Issues",
    "Digital Receipts and Invoices",
    "Website Navigation Difficulties",
    "Virtual Class Video Quality",
    "Studio Wi-Fi Not Working",
  ],
  "Pricing and Memberships": [
    "Price Transparency",
    "Membership Flexibility",
    "Discounts and Offers Confusion",
    "Refund and Cancellation Policy Issue",
    "Auto-Renewal Concerns",
    "Transparency in TandC",
    "Add-on Services Pricing Clarity",
    "Class Pack Expiry Confusion",
    "Private Session Pricing",
    "Membership Upgrade/Downgrade",
    "Lack of Payment Plan Options",
    "Referral Discount Issues",
    "Holiday and Special Pricing Clarity",
    "Corporate Wellness Program Pricing",
    "Pricing for International Clients",
    "Membership Pause and Freeze Policy",
    "Special Group Discounts",
    "Loyalty Program Issues",
  ],
  "Customer Service and Communication": [
    "Delay in Response",
    "Unresolved Complaints",
    "Front Desk Attitude",
    "Miscommunication on Offers",
    "Response Time to Queries",
    "Follow-up Post Inquiry",
    "Friendliness and Approachability",
    "Call Handling Etiquette",
    "Clarity in Policies",
    "Late Response to Complaints",
    "Handling of Complaints",
    "Feedback Follow-up Process",
    "Compensation for Service Issues",
    "Customer Retention Strategies",
    "Over-promising and Under-delivery",
    "Response to Negative Reviews",
    "Training of Customer Service Team",
    "Training of Sales Team",
    "Knowledge of Membership Policies",
    "Proactive Client Engagement",
  ],
  "Brand Feedback": [
    "Brand Positioning",
    "Brand Identity Consistency",
    "Marketing Message Accuracy",
    "Brand Tone Consistency",
    "Social Media Engagement",
    "Advertising Consistency",
    "Collaborations and Partnerships",
    "Merchandise Quality",
    "Member Recognition Efforts",
    "Influencer Engagement",
    "Staff Wearing Incorrect Branding",
    "Merchandise Display Issues",
    "Branded Content Guidelines",
    "Member Recognition Events",
    "Newsletter Effectiveness",
    "Brand Perception in Market",
    "Perception of Pricing Value",
    "Client Testimonials Management",
    "Client Loyalty Recognition",
    "Brand Event Participation",
  ],
  "Safety and Security": [
    "Emergency Exits Blocked",
    "Panic Button Malfunction",
    "Unlocked Doors",
    "CCTV Malfunction",
    "Security Guard Issues",
    "Client Harassment Reports",
    "Fire Drills Not Conducted",
    "Suspicious Individuals Inside Studio",
    "Front Desk Not Checking IDs",
    "Unregistered Walk-ins",
    "Trespassing Concerns",
    "Personal Safety Concerns",
    "Harassment Reports",
    "Data Breach Concerns",
    "Employee Security Training",
    "Reporting Suspicious Activity",
    "Staff Security Concerns",
    "Handling of Medical Emergencies",
    "First Aid Kit Availability",
    "Unauthorized Use of Equipment",
  ],
  "Theft and Lost Items": [
    "Locker Theft",
    "Stolen Personal Items",
    "Misplaced Valuables",
    "Items Taken from Boutique",
    "Items Left Behind by Clients",
    "Studio Lost and Found Management",
    "Staff Theft",
    "Reporting Stolen Items",
    "Theft Prevention Measures",
    "Theft Investigation Process",
    "Personal Items Taken from Trainer Area",
    "Issues with Valet Theft",
    "Theft by Other Members",
    "Lost Shoes/Workout Gear",
    "Safe Storage for Client Bags",
    "Clients Forgetting Items in Studio",
    "Missing Towels",
    "Theft During Busy Hours",
    "Members Taking Extra Equipment",
    "Coffee and Refreshments Options",
  ],
  Miscellaneous: [
    "Music Volume Issues",
    "Studio Decor and Ambience",
    "Mobile Charging Stations",
    "Late-Night Class Safety",
    "Noise Complaints from Neighbors",
    "Misplaced Equipment",
    "Temperature Control Inconsistency",
    "Scent Sensitivities",
    "Lighting Preferences",
    "Cold Air Drafts",
    "Overcrowding in Lobby",
    "Construction Noise Nearby",
    "Child-Friendly Facilities",
    "Outdoor Signage Visibility",
    "Feedback Fatigue",
    "Personal Storage Lockers Needed",
    "Background Music Selection",
    "Social Media Response Time",
    "Customer Flow Management",
    "Internal Operations / Handover",
  ],
};

export const CATEGORY_META: Record<string, CategoryMeta> = {
  Scheduling: {
    name: "Scheduling",
    icon: "🗓️",
    accent: "#6366f1",
    team: "Studio Operations",
    blurb: "Class timings, bookings, waitlists and substitutions",
    defaultPriority: "Medium",
    followUps: ["class", "trainer"],
  },
  "Class Experience": {
    name: "Class Experience",
    icon: "🧘",
    accent: "#ec4899",
    team: "Fitness & Programming",
    blurb: "In-class quality, flow, comfort and delivery",
    defaultPriority: "Medium",
    followUps: ["class", "trainer"],
  },
  "Trainer Feedback": {
    name: "Trainer Feedback",
    icon: "💪",
    accent: "#f97316",
    team: "Training Academy",
    blurb: "Instructor conduct, coaching quality and punctuality",
    defaultPriority: "Medium",
    followUps: ["trainer", "class"],
  },
  "Repair and Maintenance": {
    name: "Repair and Maintenance",
    icon: "🛠️",
    accent: "#0ea5e9",
    team: "Facilities",
    blurb: "Broken equipment, HVAC, plumbing, upkeep",
    defaultPriority: "High",
    followUps: ["location"],
  },
  "Studio Amenities and Facilities": {
    name: "Studio Amenities and Facilities",
    icon: "🚿",
    accent: "#14b8a6",
    team: "Guest Experience",
    blurb: "Cleanliness, lockers, showers, lounge and perks",
    defaultPriority: "Medium",
    followUps: ["location"],
  },
  "Operating Systems": {
    name: "Operating Systems",
    icon: "🖥️",
    accent: "#8b5cf6",
    team: "Business Systems",
    blurb: "Momence, POS, CRM, payment and booking platforms",
    defaultPriority: "High",
    followUps: ["system"],
  },
  "Tech Issues": {
    name: "Tech Issues",
    icon: "📶",
    accent: "#3b82f6",
    team: "IT Support",
    blurb: "Hardware, Wi-Fi, mics, speakers, app performance",
    defaultPriority: "High",
    followUps: ["system", "location"],
  },
  "Pricing and Memberships": {
    name: "Pricing and Memberships",
    icon: "💳",
    accent: "#eab308",
    team: "Membership & Sales",
    blurb: "Packages, renewals, refunds, freezes and offers",
    defaultPriority: "Medium",
    followUps: ["membership"],
  },
  "Customer Service and Communication": {
    name: "Customer Service and Communication",
    icon: "💬",
    accent: "#22c55e",
    team: "Guest Experience",
    blurb: "Response times, front desk, complaint handling",
    defaultPriority: "Medium",
    followUps: ["membership"],
  },
  "Brand Feedback": {
    name: "Brand Feedback",
    icon: "✨",
    accent: "#a855f7",
    team: "Marketing & Brand",
    blurb: "Positioning, campaigns, merchandise and tone",
    defaultPriority: "Low",
    followUps: [],
  },
  "Safety and Security": {
    name: "Safety and Security",
    icon: "🛡️",
    accent: "#ef4444",
    team: "Safety & Compliance",
    blurb: "Emergencies, harassment, access control, CCTV",
    defaultPriority: "Critical",
    followUps: ["risk", "location"],
  },
  "Theft and Lost Items": {
    name: "Theft and Lost Items",
    icon: "🎒",
    accent: "#f43f5e",
    team: "Safety & Compliance",
    blurb: "Lost property, locker theft, investigations",
    defaultPriority: "High",
    followUps: ["risk", "location"],
  },
  Miscellaneous: {
    name: "Miscellaneous",
    icon: "🧩",
    accent: "#64748b",
    team: "Studio Operations",
    blurb: "Ambience, music, signage and everything else",
    defaultPriority: "Low",
    followUps: ["location"],
  },
};

export const CATEGORIES = Object.keys(TAXONOMY);

/** Extra vocabulary that helps the classifier map natural language to a subcategory. */
export const SUBCATEGORY_HINTS: Record<string, string[]> = {
  "Repair and Maintenance::AC and HVAC Issues": [
    "ac", "air conditioner", "aircon", "hvac", "cooling", "not cooling", "heater", "chiller",
  ],
  "Repair and Maintenance::Plumbing Leaks": ["leak", "leaking", "water on floor", "tap", "faucet", "pipe", "flooded", "drain"],
  "Repair and Maintenance::Lighting Issues": ["light", "lights", "bulb", "flickering", "dark", "tube light"],
  "Repair and Maintenance::Pest Control Needed": ["cockroach", "rat", "mice", "ants", "pest", "insects", "mosquito"],
  "Repair and Maintenance::Broken Equipment Not Repaired": ["broken", "barre", "bar loose", "ball punctured", "band torn", "weights", "equipment damaged", "mat torn"],
  "Repair and Maintenance::Towel Availability Issues": ["towel", "towels", "no towels"],
  "Repair and Maintenance::Toiletries and Supplies Low": ["shampoo", "soap", "toiletries", "tissue", "sanitizer", "supplies"],
  "Repair and Maintenance::Door Lock Issues": ["door lock", "latch", "lock broken", "door jam"],
  "Repair and Maintenance::Water Dispenser Issues": ["water dispenser", "water cooler", "drinking water"],
  "Repair and Maintenance::Music System Too Loud/Low": ["music system", "volume", "speaker volume"],
  "Repair and Maintenance::Dust and Mold in Corners": ["dust", "mold", "mould", "fungus", "damp"],
  "Studio Amenities and Facilities::Cleanliness and Hygiene": ["dirty", "unclean", "hygiene", "not cleaned", "washroom dirty", "toilet dirty", "filthy"],
  "Studio Amenities and Facilities::Shower Water Pressure": ["shower", "water pressure", "hot water", "geyser"],
  "Studio Amenities and Facilities::Locker Availability": ["locker", "no lockers", "locker full"],
  "Studio Amenities and Facilities::Wi-Fi Slow": ["wifi slow", "internet slow", "slow wifi"],
  "Studio Amenities and Facilities::Valet Issues": ["valet", "parking", "car park", "driver"],
  "Studio Amenities and Facilities::Steam Room Not Working": ["steam room", "sauna"],
  "Studio Amenities and Facilities::Studio Odour and Aroma": ["smell", "odour", "odor", "stink", "aroma"],
  "Class Experience::Bad Odour": ["smell in class", "bad smell", "sweaty smell", "stinks", "odour in studio"],
  "Class Experience::Audio Issues": ["music too loud", "cannot hear", "audio", "sound cutting", "playlist"],
  "Class Experience::Studio Temperature Too Hot/Cold": ["too hot", "too cold", "stuffy", "freezing", "sweltering", "temperature"],
  "Class Experience::Overcrowding in Class": ["overcrowded", "too many people", "packed class", "no space", "crowded"],
  "Class Experience::Instructor Energy and Motivation": ["low energy", "not motivating", "dull class", "no enthusiasm"],
  "Trainer Feedback::Trainer Punctuality Issues": ["trainer late", "instructor late", "started late", "came late"],
  "Trainer Feedback::Trainer Behaviour": ["rude trainer", "trainer behaviour", "trainer behavior", "impolite", "attitude of trainer"],
  "Trainer Feedback::Trainer Hygiene": ["trainer smell", "body odour", "trainer hygiene", "unkempt"],
  "Trainer Feedback::Class Intensity Too High/Low": ["too intense", "too easy", "too hard", "intensity"],
  "Trainer Feedback::Injury Prevention and Safety": ["injury", "injured", "hurt", "pain", "sprain", "unsafe form"],
  "Trainer Feedback::Trainer Forgot Names": ["forgot name", "did not know my name", "names"],
  "Scheduling::Time Change": ["change timing", "time change", "shift the class", "reschedule time", "earlier slot", "later slot"],
  "Scheduling::Waitlist Concerns": ["waitlist", "wait list", "queue for class"],
  "Scheduling::Class Capacity Issues": ["class full", "capacity", "no slots", "fully booked"],
  "Scheduling::Additional Classes": ["more classes", "add a class", "extra class", "additional slot"],
  "Scheduling::Last-minute Cancellations": ["cancelled last minute", "class cancelled", "sudden cancellation"],
  "Scheduling::Trainer Substitutions": ["substitute trainer", "different instructor", "sub trainer", "replacement trainer"],
  "Scheduling::Booking Confirmation Issues": ["no confirmation", "booking not confirmed", "confirmation mail"],
  "Operating Systems::Moments Notice": ["momence", "moments notice", "mn system", "booking software"],
  "Operating Systems::Stripe and Razorpay": ["stripe", "razorpay", "payment gateway"],
  "Operating Systems::POS System Malfunctions": ["pos", "billing machine", "card machine", "swipe machine"],
  "Operating Systems::CRM System Errors": ["crm", "customer database", "lead record"],
  "Operating Systems::Attendance Record Discrepancies": ["attendance", "check in not recorded", "session not deducted"],
  "Operating Systems::iPad Functionality": ["ipad", "tablet"],
  "Operating Systems::Router Connectivity": ["router", "network down", "connectivity"],
  "Tech Issues::Mic Not Working": ["mic", "microphone", "headset", "mic dead"],
  "Tech Issues::Speakers Static Noise": ["speaker", "static", "crackling", "distorted sound"],
  "Tech Issues::Studio Wi-Fi Not Working": [
    "wifi", "wifi down", "wifi not working", "internet down", "no internet", "network down", "internet not working",
  ],
  "Tech Issues::Password and Login Issues": ["login", "password", "cannot sign in", "otp"],
  "Tech Issues::Payment Processing Delays": ["payment failed", "payment stuck", "transaction pending"],
  "Tech Issues::Incorrect Charges on Account": ["charged twice", "wrong charge", "double charged", "overcharged"],
  "Tech Issues::Laptops Not Functioning": ["laptop", "computer not working", "desktop"],
  "Tech Issues::Booking System Errors": ["cannot book", "booking error", "app booking failed"],
  "Pricing and Memberships::Refund and Cancellation Policy Issue": [
    "refund", "money back", "cancel membership", "wants a refund", "full refund",
    "charged twice", "double charged", "duplicate charge", "reverse the charge", "chargeback",
  ],
  "Pricing and Memberships::Auto-Renewal Concerns": ["auto renew", "auto-debit", "renewed without asking"],
  "Pricing and Memberships::Membership Pause and Freeze Policy": ["freeze", "pause membership", "hold membership"],
  "Pricing and Memberships::Class Pack Expiry Confusion": ["expired classes", "pack expiry", "credits expired"],
  "Pricing and Memberships::Membership Upgrade/Downgrade": ["upgrade", "downgrade", "change plan"],
  "Pricing and Memberships::Price Transparency": ["price not clear", "hidden charges", "pricing confusion"],
  "Customer Service and Communication::Front Desk Attitude": ["front desk rude", "reception attitude", "staff rude", "receptionist"],
  "Customer Service and Communication::Delay in Response": ["no response", "nobody replied", "waiting for reply", "delay in response"],
  "Customer Service and Communication::Unresolved Complaints": ["complaint not resolved", "still pending", "raised earlier"],
  "Safety and Security::Client Harassment Reports": ["harassment", "harassed", "inappropriate behaviour", "misconduct", "stalking"],
  "Safety and Security::Emergency Exits Blocked": ["fire exit", "emergency exit", "exit blocked"],
  "Safety and Security::CCTV Malfunction": ["cctv", "camera not working", "surveillance"],
  "Safety and Security::Handling of Medical Emergencies": [
    "fainted", "collapsed", "ambulance", "medical emergency", "unconscious",
    "slipped", "slip and fall", "fell", "tripped", "hurt her", "hurt his", "injured",
    "twisted ankle", "sprained", "wrist", "bleeding", "first aid", "wet patch", "wet floor",
  ],
  "Safety and Security::First Aid Kit Availability": ["first aid", "band aid", "medical kit"],
  "Safety and Security::Suspicious Individuals Inside Studio": ["suspicious", "stranger", "unknown person"],
  "Theft and Lost Items::Locker Theft": ["locker theft", "stolen from locker", "locker broken into"],
  "Theft and Lost Items::Stolen Personal Items": ["stolen", "theft", "missing wallet", "phone stolen", "jewellery missing"],
  "Theft and Lost Items::Clients Forgetting Items in Studio": ["left behind", "forgot my", "lost item", "left her", "left his"],
  "Theft and Lost Items::Lost Shoes/Workout Gear": ["lost shoes", "missing socks", "workout gear missing"],
  "Brand Feedback::Merchandise Quality": ["merch", "merchandise", "apparel quality", "leggings"],
  "Brand Feedback::Social Media Engagement": ["instagram", "social media", "reels", "posts"],
  "Miscellaneous::Music Volume Issues": ["music volume", "too loud music", "music low"],
  "Miscellaneous::Studio Decor and Ambience": ["decor", "ambience", "interiors", "vibe of studio"],
  "Miscellaneous::Overcrowding in Lobby": ["lobby crowded", "reception crowded", "waiting area full"],
  "Miscellaneous::Noise Complaints from Neighbors": ["neighbour", "neighbor complaint", "noise complaint"],
};

export const CATEGORY_HINTS: Record<string, string[]> = {
  Scheduling: ["schedule", "timing", "slot", "booking", "class time", "waitlist", "calendar"],
  "Class Experience": ["class", "session", "workout", "during class", "studio floor"],
  "Trainer Feedback": ["trainer", "instructor", "coach", "teacher"],
  "Repair and Maintenance": ["broken", "repair", "fix", "not working", "maintenance", "damaged"],
  "Studio Amenities and Facilities": ["locker", "shower", "washroom", "lounge", "amenity", "facility", "clean"],
  "Operating Systems": ["system", "software", "momence", "pos", "crm", "platform"],
  "Tech Issues": ["tech", "device", "wifi", "mic", "speaker", "app", "laptop", "hardware"],
  "Pricing and Memberships": [
    "price", "membership", "package", "refund", "payment plan", "renewal", "credits",
    "charged", "billing", "invoice", "auto debit", "unlimited pack", "class pack",
  ],
  "Customer Service and Communication": ["front desk", "response", "reply", "communication", "service", "complaint"],
  "Brand Feedback": ["brand", "marketing", "campaign", "merch", "social"],
  "Safety and Security": [
    "safety", "security", "emergency", "harassment", "unsafe", "guard",
    "injury", "injured", "slipped", "fell", "hurt", "accident", "first aid",
  ],
  "Theft and Lost Items": ["theft", "stolen", "missing", "lost", "lost and found"],
  Miscellaneous: ["other", "misc", "general"],
};

export function subcategoriesFor(category: string): string[] {
  return TAXONOMY[category] ?? [];
}

export function metaFor(category: string): CategoryMeta {
  return CATEGORY_META[category] ?? CATEGORY_META.Miscellaneous;
}

export function priorityColor(priority: string): string {
  switch (priority) {
    case "Critical":
      return "bg-red-500/15 text-red-600 ring-red-500/30";
    case "High":
      return "bg-orange-500/15 text-orange-600 ring-orange-500/30";
    case "Medium":
      return "bg-amber-400/15 text-amber-600 ring-amber-500/30";
    default:
      return "bg-emerald-500/15 text-emerald-600 ring-emerald-500/30";
  }
}

export function statusColor(status: string): string {
  switch (status) {
    case "Open":
      return "bg-sky-500/15 text-sky-600 ring-sky-500/30";
    case "In Progress":
      return "bg-violet-500/15 text-violet-600 ring-violet-500/30";
    case "Awaiting Info":
      return "bg-amber-500/15 text-amber-700 ring-amber-500/30";
    case "Resolved":
      return "bg-emerald-500/15 text-emerald-600 ring-emerald-500/30";
    default:
      return "bg-slate-500/15 text-slate-600 ring-slate-500/30";
  }
}
